version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db_kitty:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kolian338/kittygram_backend
    env_file: .env
    depends_on:
      - db_kitty
    volumes:
      - static:/static
      - media:/app/media/
  frontend:
    env_file: .env
    image: kolian338/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: kolian338/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - backend
